[package]
name = "rpc-replay"
version = "0.1.0"
edition = "2021"

[dependencies]
blockifier = { workspace = true }
starknet_api = { workspace = true }
arcane-os-type = { workspace = true }
thiserror = { workspace = true }
starknet = { workspace = true }
